### ISSUE TITLE
Is this source still actual?

### ISSUE THREAD

**Issue by plachta11b** [Ne0nx3r0/BetterAlias#5]
I find last update of betteralias on bukkit plugin page is Mar 19, 2015 but this source has last commit in 2013. Can you update this repository?

**Comment by Ne0nx3r0** [comment]
I'll check and see tonight what I have at home, to be honest that was a year ago and my memory is a little foggy.

**Comment by Ne0nx3r0** [comment]
Take a look at https://github.com/Ne0nx3r0/BetterAlias/commit/f5f2d72aa759d1b0229798c522006971f2fc92cf

Mostly formatting changes it seems, but the version matches. Unfortunately I don't have the version control for the changes so I had to do it in one batch.

**Comment by plachta11b** [comment]
Thanks. I try implement new feature so I am happy to see that you are still active.
